# Generated by Django 5.1.5 on 2025-02-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=50, unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('parked_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
