# Generated by Django 5.1.5 on 2025-02-01 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDetail',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingDetail',
            fields=[
                ('parking_id', models.AutoField(primary_key=True, serialize=False)),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('parking_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_before', models.BooleanField(default=False)),
                ('status_after', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingPlace',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_date', models.DateTimeField()),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('User', 'User')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('vehicle_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_reg_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ParkingSlot',
        ),
        migrations.AddField(
            model_name='parkingdetail',
            name='lot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkinglot'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='parking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingplace'),
        ),
        migrations.AddField(
            model_name='parkingdetail',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingplace'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='parking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingdetail'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.user'),
        ),
        migrations.AddField(
            model_name='parkingdetail',
            name='occupied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.user'),
        ),
        migrations.AddField(
            model_name='logdetail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.user'),
        ),
        migrations.AddField(
            model_name='parkingdetail',
            name='vehicle_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicletype'),
        ),
    ]
